# Generated by Django 2.0.1 on 2018-11-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='class_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
