# Generated by Django 2.0.1 on 2018-11-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_chat_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='class_name',
            new_name='class_id',
        ),
    ]
