# Generated by Django 2.0.1 on 2018-11-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20181103_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='name',
            new_name='user_name',
        ),
    ]
