# Generated by Django 2.0.1 on 2018-11-04 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_auto_20181104_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatNode',
            fields=[
                ('chat_unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='unknown', max_length=50)),
                ('content', models.CharField(default='', max_length=50)),
                ('class_id', models.CharField(default='', max_length=50)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 11, 4, 17, 20, 59, 373010))),
                ('ddabong', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
