# Generated by Django 2.0.1 on 2018-11-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0013_auto_20181104_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-05 06:37:57', max_length=50),
        ),
    ]
