# Generated by Django 2.0.1 on 2018-11-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0014_auto_20181105_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.CharField(default='', max_length=50)),
                ('class_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-06 00:10:28', max_length=50),
        ),
    ]
