# Generated by Django 2.0.1 on 2018-11-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0015_auto_20181106_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(default='', max_length=50)),
                ('class_code', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-07 18:02:06', max_length=50),
        ),
    ]
