# Generated by Django 2.0.1 on 2018-11-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0016_auto_20181107_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassNode',
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-07 18:16:22', max_length=50),
        ),
    ]
