# Generated by Django 2.0.1 on 2018-11-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0018_auto_20181107_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnode',
            name='number_of_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classnode',
            name='user_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-08 11:31:15', max_length=50),
        ),
    ]
