# Generated by Django 2.0.1 on 2018-11-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0019_auto_20181108_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classnode',
            old_name='class_code',
            new_name='class_id',
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-08 11:33:05', max_length=50),
        ),
    ]
