# Generated by Django 2.0.1 on 2018-11-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0020_auto_20181108_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(default='', upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-08 19:15:32', max_length=50),
        ),
    ]
