# Generated by Django 2.0.1 on 2018-11-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0023_auto_20181108_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-08 19:51:59', max_length=50),
        ),
    ]
