# Generated by Django 2.0.1 on 2018-11-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0024_auto_20181108_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_name', models.CharField(default='', max_length=50)),
                ('user_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('user_psw', models.CharField(default='', max_length=50)),
                ('user_email', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-10 14:37:10', max_length=50),
        ),
    ]
