# Generated by Django 2.0.1 on 2018-11-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0025_auto_20181110_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnode',
            name='founder',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-10 15:47:08', max_length=50),
        ),
    ]
