# Generated by Django 2.0.1 on 2018-11-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0026_auto_20181110_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classnode',
            old_name='founder',
            new_name='founder_id',
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-10 15:48:19', max_length=50),
        ),
    ]
