# Generated by Django 2.0.1 on 2018-11-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0027_auto_20181110_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('user_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('class_name', models.CharField(default='', max_length=50)),
                ('class_id', models.CharField(default='', max_length=50)),
                ('founder_id', models.CharField(default='', max_length=50)),
                ('memo', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-17 14:38:34', max_length=50),
        ),
    ]
