# Generated by Django 2.0.1 on 2018-11-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0028_auto_20181117_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='in_class_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-11-18 15:04:17', max_length=50),
        ),
    ]
