# Generated by Django 2.1.1 on 2018-12-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0029_auto_20181118_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-12-07 00:57:19', max_length=50),
        ),
    ]
