# Generated by Django 2.1.1 on 2018-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0031_auto_20181207_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnode',
            name='created_date',
            field=models.CharField(default='2018-12-07', max_length=50),
        ),
        migrations.AddField(
            model_name='classnode',
            name='image',
            field=models.ImageField(default='classImg/LYAN1.jpg', upload_to='classImg/'),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-12-07 01:05:24', max_length=50),
        ),
    ]
