# Generated by Django 2.1.1 on 2018-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0032_auto_20181207_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnode',
            name='founder_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='created_date',
            field=models.CharField(default='2018-12-07 01:16:07', max_length=50),
        ),
    ]
